import type { Metadata } from "next";
import "./globals.css";
import RecoilRootWrapper from "../components/wrapper/RecoilWrapper";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export const metadata: Metadata = {
  title: "LeetCode",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <RecoilRootWrapper>
        <body className="">{children}</body>
        <ToastContainer />
      </RecoilRootWrapper>
    </html>
  );
}
