import type { Metadata } from "next";
import "./globals.css";
import RecoilRootWrapper from "../components/wrapper/RecoilWrapper";

export const metadata: Metadata = {
  title: "LeetCode",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <RecoilRootWrapper>
        <body className="">{children}</body>
      </RecoilRootWrapper>
    </html>
  );
}
